import { PhrasalVerb, phrasalId } from "../domain/entities/PhrasalVerb";

export const PHRASAL_VERBS_SEED: PhrasalVerb[] = [
  {
    id: phrasalId("get up"),
    verb: "get up",
    particles: ["up"],
    baseVerb: "get",
    ipa: "/ɡɛt ʌp/",
    meaning: "levantarse",
    separable: false,
    formality: "casual",
    synonym: "rise",
    examples: [
      { en: "I get up at 6am.", es: "Me levanto a las 6 de la mañana." },
    ],
  },
  {
    id: phrasalId("give up"),
    verb: "give up",
    particles: ["up"],
    baseVerb: "give",
    ipa: "/ɡɪv ʌp/",
    meaning: "rendirse",
    separable: false,
    formality: "neutral",
    synonym: "surrender",
    examples: [{ en: "Don't give up.", es: "No te rindas." }],
  },
  {
    id: phrasalId("look for"),
    verb: "look for",
    particles: ["for"],
    baseVerb: "look",
    ipa: "/lʊk fɔːr/",
    meaning: "buscar",
    separable: false,
    formality: "neutral",
    synonym: "search",
    examples: [{ en: "I'm looking for my keys.", es: "Estoy buscando mis llaves." }],
  },
  {
    id: phrasalId("find out"),
    verb: "find out",
    particles: ["out"],
    baseVerb: "find",
    ipa: "/faɪnd aʊt/",
    meaning: "averiguar",
    separable: true,
    formality: "neutral",
    synonym: "discover",
    examples: [{ en: "I'll find out tomorrow.", es: "Lo averiguaré mañana." }],
  },
  {
    id: phrasalId("turn on"),
    verb: "turn on",
    particles: ["on"],
    baseVerb: "turn",
    ipa: "/tɜːrn ɒn/",
    meaning: "encender",
    separable: true,
    formality: "neutral",
    synonym: "activate",
    examples: [{ en: "Turn on the lights.", es: "Enciende las luces." }],
  },
  {
    id: phrasalId("hang out"),
    verb: "hang out",
    particles: ["out"],
    baseVerb: "hang",
    ipa: "/hæŋ aʊt/",
    meaning: "pasar el rato",
    separable: false,
    formality: "casual",
    synonym: "socialise",
    examples: [{ en: "We hang out on weekends.", es: "Nos juntamos los fines de semana." }],
  },
  {
    id: phrasalId("figure out"),
    verb: "figure out",
    particles: ["out"],
    baseVerb: "figure",
    ipa: "/ˈfɪɡjər aʊt/",
    meaning: "descifrar / entender",
    separable: true,
    formality: "neutral",
    synonym: "comprehend",
    examples: [{ en: "I can't figure out this puzzle.", es: "No puedo descifrar este rompecabezas." }],
  },
  {
    id: phrasalId("come up with"),
    verb: "come up with",
    particles: ["up", "with"],
    baseVerb: "come",
    ipa: "/kʌm ʌp wɪð/",
    meaning: "ocurrirse / proponer",
    separable: false,
    formality: "neutral",
    synonym: "propose",
    examples: [{ en: "She came up with a plan.", es: "Se le ocurrió un plan." }],
  },
];
